version: '3.8'
services:
  dg_api:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - dg_db

  dg_db:
    container_name: dg_backend_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: dg_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306